# M1 Informatique IM2AG-UGA
# SipHash_demo:
# Borne Jonathan - Duverney Thomas

CC=gcc
INCLUDE= -I $(PWD)
CFLAGS= -Wall -Werror -std=c99 -g $(INCLUDE)
COMPILOPTS= $(CFLAGS)
PROGRAMS= sipHash_Demo

.PHONY: clean all

all: $(PROGRAMS)
	./sipHash_Demo

# nettoyage
clean:
	rm -f *.o $(PROGRAMS)
